declare namespace NodeJS {
  interface ProcessEnv {
    // Firebase
    /// Front
    NEXT_PUBLIC_FIREBASE_FRONT_API_KEY?: string;
    NEXT_PUBLIC_FIREBASE_FRONT_AUTH_DOMAIN?: string;
    NEXT_PUBLIC_FIREBASE_FRONT_PROJECT_ID?: string;
    NEXT_PUBLIC_FIREBASE_FRONT_STORAGE_BUCKET?: string;
    NEXT_PUBLIC_FIREBASE_FRONT_MESSAGING_SENDER_ID?: string;
    NEXT_PUBLIC_FIREBASE_FRONT_APP_ID?: string;
    NEXT_PUBLIC_FIREBASE_FRONT_MEASUREMENT_ID?: string;
    /// Back
    FIREBASE_BACK_API_KEY?: string;
    FIREBASE_BACK_AUTH_DOMAIN?: string;
    FIREBASE_BACK_PROJECT_ID?: string;
    FIREBASE_BACK_STORAGE_BUCKET?: string;
    FIREBASE_BACK_MESSAGING_SENDER_ID?: string;
    FIREBASE_BACK_APP_ID?: string;
    FIREBASE_BACK_MEASUREMENT_ID?: string;
  }
}
