import {
  MakeOrderAppBar,
  MakeOrderBilling,
  MakeOrderProductSelect,
  MakeOrderStepper,
} from '@/components';
import { MakeOrderForm } from '@/types';
import Head from 'next/head';
import { FormProvider, useForm } from 'react-hook-form';

const MakeOrder = () => {
  const formMethods = useForm<MakeOrderForm>({
    defaultValues: {
      steps: { activeStep: 0, completedSteps: [] },
      selectedProducts: [
        {
          image: {
            alt: '',
            src: 'https://cdn.colombia.com/gastronomia/2011/08/04/natilla-3039.jpg',
          },
          name: 'Natilla',
          price: 5000,
          quantity: 30,
          index: 0,
        },
      ],
      billingInformation: {
        billingType: 'charge',
        documentNumber: undefined,
        documentType: '',
        email: '',
        lastName: '',
        name: '',
        phoneNumber: undefined,
        businessName: '',
      },
    },
  });

  const { watch } = formMethods;

  const activeStep = watch('steps.activeStep');

  return (
    <>
      <Head>
        <title>Pedidos - Hacer pedido</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <FormProvider {...formMethods}>
        <div style={{ width: '100%', paddingTop: 24, paddingBottom: 64 + 8 }}>
          <MakeOrderStepper />
          {activeStep === 0 && <MakeOrderProductSelect />}
          {activeStep === 1 && <MakeOrderBilling />}
        </div>
        <MakeOrderAppBar />
      </FormProvider>
    </>
  );
};

export default MakeOrder;
