import { MakeOrderStepper } from '@/components';
import { MakeOrderForm } from '@/types';
import Head from 'next/head';
import { useEffect } from 'react';
import { FormProvider, useForm } from 'react-hook-form';

const MakeOrder = () => {
  const formMethods = useForm<MakeOrderForm>({
    defaultValues: { steps: { activeStep: 0, completedSteps: [] } },
  });

  const { setValue, getValues } = formMethods;

  useEffect(() => {
    setValue('steps.completedSteps', [
      ...getValues().steps.completedSteps,
      0,
      1,
      2,
    ]);
  }, []);

  return (
    <>
      <Head>
        <title>Pedidos - Hacer pedido</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <FormProvider {...formMethods}>
        <MakeOrderStepper />
      </FormProvider>
    </>
  );
};

export default MakeOrder;
